### ISSUE TITLE
Update with new icon

### ISSUE THREAD

**Issue by alexcombessie** [dataiku/dss-plugin-emr-clusters#4]
A new icon is available in master:
https://github.com/dataiku/dip/blob/8a329c743447e5394f04cc78dbc54c67fe7c53c2/src/main/platypus/static/dataiku/css/font.less#L1508

To guarantee back-compatibility, you can use this syntax
"icon": "icon-amazon-emr icon-cloud"

**Comment by alexcombessie** [comment]
👋  @FChataigner (small UX thing)

**Comment by alexcombessie** [comment]
Hello @jbelafa! 
Any chance we can use our custom icon (comes with DSS8)?
Cheers,
Alex

**Comment by alexcombessie** [comment]
🆙  @hrjn

**Comment by alexcombessie** [comment]
🙃   @hrjn ?

**Comment by hrjn** [comment]
[Done](https://github.com/dataiku/dss-plugin-emr-clusters/commit/f75a8d750c68b5f0fb6bdd65160441431fdf2f9f), sorry for the delay 🙂
